export const ARM_LENGTH = 5
export const ARM_WIDTH = 5
export const TRIANGLE_SIZE = 5
export const TRIANGLE_OVERHANG = 2

const moveArrow = new Path2D()
export default moveArrow

const SIZE = TRIANGLE_SIZE * 2 + ARM_LENGTH * 2 + ARM_WIDTH
const CENTRE = SIZE / 2

const ARM_HALF_WIDTH = ARM_WIDTH / 2
const TRIANGLE_HALF_WIDTH = ARM_WIDTH / 2 + TRIANGLE_OVERHANG
const ARM_LENGTH_INNER = ARM_HALF_WIDTH + ARM_LENGTH

moveArrow.moveTo(CENTRE, 0)

moveArrow.lineTo(CENTRE + TRIANGLE_HALF_WIDTH, TRIANGLE_SIZE)
moveArrow.lineTo(CENTRE + ARM_HALF_WIDTH, TRIANGLE_SIZE)

moveArrow.lineTo(CENTRE + ARM_HALF_WIDTH, CENTRE - ARM_HALF_WIDTH)

moveArrow.lineTo(CENTRE + ARM_LENGTH_INNER, CENTRE - ARM_HALF_WIDTH)
moveArrow.lineTo(CENTRE + ARM_LENGTH_INNER, CENTRE - TRIANGLE_HALF_WIDTH)

moveArrow.lineTo(SIZE, CENTRE)

moveArrow.lineTo(CENTRE + ARM_LENGTH_INNER, CENTRE + TRIANGLE_HALF_WIDTH)
moveArrow.lineTo(CENTRE + ARM_LENGTH_INNER, CENTRE + ARM_HALF_WIDTH)

moveArrow.lineTo(CENTRE + ARM_HALF_WIDTH, CENTRE + ARM_HALF_WIDTH)

moveArrow.lineTo(CENTRE + ARM_HALF_WIDTH, CENTRE + ARM_LENGTH_INNER)
moveArrow.lineTo(CENTRE + TRIANGLE_HALF_WIDTH, CENTRE + ARM_LENGTH_INNER)

moveArrow.lineTo(CENTRE, SIZE)

moveArrow.lineTo(CENTRE - TRIANGLE_HALF_WIDTH, CENTRE + ARM_LENGTH_INNER)
moveArrow.lineTo(CENTRE - ARM_HALF_WIDTH, CENTRE + ARM_LENGTH_INNER)

moveArrow.lineTo(CENTRE - ARM_HALF_WIDTH, CENTRE + ARM_HALF_WIDTH)

moveArrow.lineTo(CENTRE - ARM_LENGTH_INNER, CENTRE + ARM_HALF_WIDTH)
moveArrow.lineTo(CENTRE - ARM_LENGTH_INNER, CENTRE + TRIANGLE_HALF_WIDTH)

moveArrow.lineTo(0, CENTRE)

moveArrow.lineTo(CENTRE - ARM_LENGTH_INNER, CENTRE - TRIANGLE_HALF_WIDTH)
moveArrow.lineTo(CENTRE - ARM_LENGTH_INNER, CENTRE - ARM_HALF_WIDTH)

moveArrow.lineTo(CENTRE - ARM_HALF_WIDTH, CENTRE - ARM_HALF_WIDTH)

moveArrow.lineTo(CENTRE - ARM_HALF_WIDTH, CENTRE - ARM_LENGTH_INNER)
moveArrow.lineTo(CENTRE - TRIANGLE_HALF_WIDTH, CENTRE - ARM_LENGTH_INNER)
